### ISSUE TITLE
Crash on startup due to voice commands features

### ISSUE THREAD

**Issue by Darkmega18** [Hialus/NotEnoughKeys#1]
G'day, my friend is currently having an issue with the mod crashing. It suddenly happened after we had been playing a small modpack I had assembled for us to play. just one night it just eventually had enough and started giving us this crash report constantly:
[crash-2019-06-08_23.19.31-client.txt](https://github.com/Hialus/NotEnoughKeys/files/3269296/crash-2019-06-08_23.19.31-client.txt)
She says it happens during phase 7 of the game loading process. do you know what it's related to and anything we can attempt to get rid of this crash? so far all we can do is take the mod out but that spaghettifies the controls and stuff.

**Comment by Hialus** [comment]
I'm sorry for never answering. I don't know why, but GitHub never notfied me about this issue.
Since this issue is 2 years old I will simply close this issue for now. In case this is still relevant please let me know.

**Comment by Darkmega18** [comment]
well, being as old as it was, we of course moved onto other things, can't remember what happened to the bug or what we did about it. so I guess not relevant anymore.
