### ISSUE TITLE
This mod on 1.12.2 stops working when I have a massive lag spike

### ISSUE THREAD

**Issue by A5TC** [Hialus/NotEnoughKeys#2]
I have noticed this mod stops working whenever I have a massive lag spike,  It seems that the mod does not like having really bad frame rate. I do enjoy this mod I would like to see a fix for this Issue. I love using this mod for teleporting items and XP to myself, in conjunction with World Edit's Drain liquids feature.

 PS sorry for the really broken English.

 I'm using an Core i5 Intel system in a Lenovo ideapad.

 Forgot to mention that I have a 112 different  Active mods installed.

**Comment by Hialus** [comment]
I'm sorry for never answering. I don't know why, but GitHub never notfied me about this issue.
This is sadly something that I can not fix. Speech recognition is a quite a resource intensive task and Sphinx 4 works best when using a good micrphone and having enough computing power available. Obviously during a lag spike the latter is not the case, so Sphinx 4 is unable to properly recognize what you say.
